### ISSUE TITLE
Properly managing Argobots pool

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc/mochi-margo#114]
Right now Margo's initialization will create Argobots pool using `ABT_pool_create_basic` for "built-in" pool types, or `ABT_pool_create` for the "prio_wait" pool type added by Phil.  `ABT_pool_create_basic` has an "automatic" argument that tells Argobots to automatically free the pool when the pool is no longer used by any ES. This is why Margo doesn't have to call `ABT_pool_free` by itself. However this poses a number of problems:

- If the user specifies a pool in the JSON configuration but does not associate it with any ES, this pool will be created by Margo but never destroyed by Argobots (unless of course the user manually associates that pool with an ES later on);
- The pools created using `ABT_pool_create` (right now pools of type "prio_wait") won't be freed at all because `ABT_pool_create` doesn't have an "automatic" argument.

Note that the fix isn't as simple as tracking which pool is a "basic" and which pool is custom, and calling `ABT_pool_free` only on custom pools, because a custom pool may have been associated with the primary ES and it's not allowed to call `ABT_pool_free` on a pool used by the primary ES. I don't know how we are supposed to free a pool associated with the primary ES. Maybe a solution would be to first replace the primary ES's pool with a basic pool, with automatic=TRUE, then call `ABT_pool_free` on the custom pool.

**Comment by mdorier** [comment]
Note from Shintaro:

> If a pool created by ABT_pool_create() is associated with the primary execution stream (and thus automatic = false), you do not need to free it explicitly. ABT_finalize() will free everything that is associated with the primary stream. If you use Argobots 1.0, doing so for a non-automatic pool might cause memory leak, though.

Later versions of Argobots have corrected this memory leak. So I think the correct way to proceed is to keep track of which pool should be freed explicitly by asking whether (1) it's a custom pool and (2) it has not been associated with the primary ES.

**Comment by carns** [comment]
This issue is causing a small memory leak in `tests/unit-tests/margo-abt-pool`, which isn't really a big deal except that it makes the test case fail when using address sanitizer.  I'll have a look.
