### ISSUE TITLE
margo-gen-profile error on mobject/ior run

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#117]
[margo-profile-2021-03-30.tar.gz](https://github.com/mochi-hpc/mochi-margo/files/6229959/margo-profile-2021-03-30.tar.gz)

When I run `margo-gen-profile` on the files in the attached tgz, I get the following error:

```
*******************MARGO Profile Generator******************
Reading CSV files from: /home/carns/working/dbg/margo-profile-2021-03-30
Traceback (most recent call last):
  File "/home/carns/working/src/spack/opt/spack/linux-ubuntu20.10-skylake/gcc-10.2.0/mochi-margo-0.9.4-c3nxr3wgzh6fjqmb2ds7pmcqwhpfekav/bin/margo-gen-profile", line 594, in <module>
    main()
  File "/home/carns/working/src/spack/opt/spack/linux-ubuntu20.10-skylake/gcc-10.2.0/mochi-margo-0.9.4-c3nxr3wgzh6fjqmb2ds7pmcqwhpfekav/bin/margo-gen-profile", line 567, in main
    p.readfiles()
  File "/home/carns/working/src/spack/opt/spack/linux-ubuntu20.10-skylake/gcc-10.2.0/mochi-margo-0.9.4-c3nxr3wgzh6fjqmb2ds7pmcqwhpfekav/bin/margo-gen-profile", line 247, in readfiles
    name, avg, rpc_breadcrumb, \
ValueError: not enough values to unpack (expected 15, got 1)
```
This example has 4 `mobject` daemons, 4 `ior` processes, and one invocation of `mobject-server-ctl` to cleanly shut down the daemons after the ior run.  I don't really care about the `mobject-server-ctl` data, but I think I'm getting the same error even if I remove it's profile files.

**Comment by carns** [comment]
Oh, it looks like some of the files (like `profile-carns-x1-7g-335060.csv`) are structured as if multiple files are concatenated.  There is data for na+sm://335060/0, followed by data for na+sm://335060/1, and so forth, all in the same .csv file.

I think the script is breaking when the csv file starts over with a new entry like that, but I'm not sure if this is something gen-profile is supposed to handle, or if this is from the daemons producing faulty  output.

**Comment by carns** [comment]
This probably happens if a process cycles through multiple margo init/finalize sequences before exiting?

**Comment by carns** [comment]
Probably the ideal behavior in this case would be for `margo_gen_profile` to detect this condition (one .csv file containing data for multiple margo instances in one pid), read them all in, and combine them as if they were data from one process.  Might need a better delimiter for the start and end of data for a given instance.

In the mean time I can probably work around it by just cutting n-1 of the data sets from the csvs that show this problem.

**Comment by carns** [comment]
Confirmed workaround; if I truncate the .csv and .diag files from the tarball attachment so that there is only one instance per file, the margo_gen_profile script seems to work fine.

**Comment by mdorier** [comment]
No longer relevant with new monitoring system. Closing.
