### ISSUE TITLE
tests/error.sh leaks memory

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#119]
This causes `make check` to fail when using aggressive address sanitizer settings.  The problem is likely in mercury itself (rather than margo or the test program) due to some address resources that need to be cleaned up on failure, but need to confirm.

**Comment by KoyamaSohei** [comment]
How did you detect memory leaks, and confirmed that the test fails? I want to try that.

If possible, I would like you to setup `make check-memoryleak` or something, thanks.

**Comment by carns** [comment]
When I'm compiling manually (outside of spack) I use this in my setup:

`export CFLAGS="-fsanitize=address -fno-omit-frame-pointer -g -Wall" && export ASAN_OPTIONS="abort_on_error=1" && export LDFLAGS="-fsanitize=address"`

I think in theory you can make spack do this as well by specifying cflags and ldflags, but I have not tried it.

**Comment by KoyamaSohei** [comment]
@carns Thanks!

**Comment by KoyamaSohei** [comment]
I confirmed that a memory leak occurred and the test failed.

```
===================================
   margo 0.9.2: ./test-suite.log
===================================

# TOTAL: 7
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/error.sh
====================

+ '[' -z .. ']'
+ '[' -z mktemp ']'
+ source ../tests/test-util.sh
++ '[' -z timeout ']'
++ mktemp --tmpdir test-XXXXXX
+ TMPOUT=/tmp/test-O4eyNy
+ svr1=na+sm://4661/0
+ sleep 1
+ run_to 10 tests/margo-test-client-error na+sm://4661/0
+ '[' 134 -ne 0 ']'
+ wait
+ cat /tmp/test-O4eyNy
+ maxtime=10s
+ shift
+ timeout --signal=9 10s tests/margo-test-client-error na+sm://4661/0
sleep 3s
sleep 3s
sleep 3s
sleep 3s

=================================================================
==61336==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f5afa048639 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f5af9ec74d3 in na_sm_addr_create /tmp/koyamaso/spack-stage/spack-stage-mercury-2.0.0-ypo3cuqdbcuwypqvxd674fxtc6s256ws/spack-src/src/na/na_sm.c:2377

SUMMARY: AddressSanitizer: 72 byte(s) leaked in 1 allocation(s).
timeout: the monitored command dumped core
../tests/test-util.sh: line 11: 61335 Aborted                 $TIMEOUT --signal=9 $maxtime "$@"
+ exit 1
FAIL tests/error.sh (exit status: 1)


```

**Comment by KoyamaSohei** [comment]
I'm currently investigating, but this is probably a mercury issue.

The following code also leaks memory, probably due to the same issue.

```
#include <mercury.h>
#include <assert.h>

int main() {
  na_class_t *class;
  na_addr_t addr = NA_ADDR_NULL;

  class = NA_Initialize("na+sm",NA_FALSE);
  assert(class != NULL);

  assert(NA_Addr_lookup(class,"na+sm://4661/0",&addr)==NA_SUCCESS);

  assert(NA_Addr_free(class,addr)==NA_SUCCESS);
  assert(NA_Finalize(class)==NA_SUCCESS);
}
```

**Comment by carns** [comment]
Thanks for narrowing that down!  Can you open an issue with that reproducer on the Mercury project?  https://github.com/mercury-hpc/mercury/issues

**Comment by KoyamaSohei** [comment]
With pleasure. ( I opened https://github.com/mercury-hpc/mercury/issues/445 )

**Comment by KoyamaSohei** [comment]
@soumagne  solves  https://github.com/mercury-hpc/mercury/issues/445 ( Thanks ! ) , and confirmed that there is no memory leak  with tests/error.sh.

**Comment by carns** [comment]
I just confirmed it as well, using the new Mercury 2.0.1rc3 tag.  Thanks for pushing on this @KoyamaSohei
