### ISSUE TITLE
unable to set pool kind for __rpc__ pool

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#142]
For configurations that use an explicit thread pool for RPC handling, it doesn't look like you can modify the "kind" of the pool (for example, to switch from "fifo_wait" to "prio_wait", which could be helpful for prioritizing ULT execution in some workloads).

It looks like the __rpc__ pool is created even if one with that name (and different parameters) already exists.  This is possibly an artifact of using the `rpc_thread_count` convenience parameter or one of the `margo_init()` variants that takes it as an integer argument.

Even if that thread count parameter is set we should honor if the corresponding pool has already been specified.

**Comment by mdorier** [comment]
Right now the code is considering that you either provided `rpc_pool` or `rpc_thread_count`, creating an `__rpc__` pool if it's the latter. But actually we could imagine having both of these parameters specified. `rpc_thread_count` is simply a helper to create N xstreams, all of which use either the pool specified by `rpc_pool`, if provided, or a default `___rpc__` pool.

**Comment by mdorier** [comment]
Solved by #143
