### ISSUE TITLE
margo_init unit test is slower than expected

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#146]
Everything works correctly, but it takes longer to cycle through init/finalize than expected.

Low priority, but it might be worth checking where the time is lost to see if anything can be done about it or not.

**Comment by mdorier** [comment]
Is the time wasted in init or finalize?

**Comment by carns** [comment]
(looking at this more than a year later) surprisingly the time appears to be taken by `margo_init()`.  Each call takes 1 second to return, and the margo-init unit test happens to call margo_init twice for each test case.

**Comment by carns** [comment]
Oh, it is the Argobots profiling interface initialization (`ABTX_prof_init()`) call.  It runs a 1 second loop to calculate a cycle/second ratio for later use.

This is only activated if Argobots is built with the +tool variant.  If that isn't used then the time to execute this unit test drops from ~37 seconds to ~7 seconds.

Closing this issue; this really doesn't matter much and wont' affect normal stack builds.

**Comment by mdorier** [comment]
I thought tests did not take that long on my laptop :-)
