### ISSUE TITLE
Segfault in margo_init when margo_addr_self fails

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc/mochi-margo#182]
This line https://github.com/mochi-hpc/mochi-margo/blob/main/src/margo-init.c#L399 assumes that the previous macro succeeded in getting a string address for the process, otherwise `strlen` segfaults. This is currently happening on Summit. The underlying problem is probably a Mercury one, but this doesn't mean we shouldn't correctly check that `name` is not `NULL` before trying to get its length.

**Comment by carns** [comment]
Looking at this a little closer, it might be best if we turned that macro into a proper function (static inline would be fine) so that it can have an obvious return value for the caller to check rather than looking for NULL in the argument.  I'll look at making that change.
