### ISSUE TITLE
add HG_Bulk_create_attr() bindings

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#184]
See https://github.com/mercury-hpc/mercury/pull/559, which adds a new Mercury API function to register GPU memory for bulk transfers.

We need a corresponding API function in Margo to go with it.  We should also explore the possibility of an (optional) autodetection feature such that margo could call the correct underlying Mercury functions based on the pointer passed into bulk create.

Requested by @Zhang690683220

**Comment by soumagne** [comment]
Just seeing your comment, I haven't exposed it but maybe we can look into it, UCX provides `UCS_MEMORY_TYPE_UNKNOWN`, that tells UCX to guess. libfabric does not have a similar feature afaik but we could maybe also do something there?

**Comment by carns** [comment]
I've got a PR ready to land to support the create_attr fn in margo once it's available in Mercury.

Thus far I haven't found anything really portable to do the memory type detection; that might have to be done at a higher level?

**Comment by Zhang690683220** [comment]
Yes, I agree that we should do the memory detection at higher level. We don't want to put the detection overhead in every network request since it is typically consistent in an application.

**Comment by carns** [comment]
Ok, thanks.  I edited the issue title just now to scope this down to just the binding for the new function.

**Comment by soumagne** [comment]
Yeah I think if the app does not know, we can just let it use the flag `HG_MEM_TYPE_UNKNOWN` (which is not exposed currently) and then we can try to do smarter with it (either let UCX handle it directly since it can support that mode or try something else with libfabric).
