### ISSUE TITLE
Use HG_Set/Get_data to improve access to RPC-related data

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc/mochi-margo#189]
In many places we have the following code to retrieve information related to the RPC (such as its pool, etc.):

```cpp
struct margo_rpc_data* rpc_data = (struct margo_rpc_data*)HG_Registered_data(hgi->hg_class, hgi->id);
```

I assume this involves a lookup in a hash table in Mercury. An optimization could be to have this called only at the beginning of the `__MARGO_INTERNAL_RPC_WRAPPER_BODY` macro, with the result being passed to `HG_Set_data` to attach it to the handle. Then anytime the rpc data is needed, we can just call `HG_Get_data` on the handle instead of `HG_Registered_data`.

We would need to provide a `margo_get_data` and a `margo_set_data` function to avoid having users call `HG_Get/Set_data`.

Note that there might be ways to similarly optimize other places in the code by using the data associated with the Mercury class/context (`HG_class/context_get/set_data`).

**Comment by carns** [comment]
Yeah, this is a good idea, especially if we aren't already using HG_Set_data() for any other purposes in Margo.

**Comment by mdorier** [comment]
Addressed via https://github.com/mochi-hpc/mochi-margo/pull/205
