### ISSUE TITLE
clarify semantics of margo_init_ext() function

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#192]
The `margo_init_ext()` function includes an `args->hg_init_info` field of type `struct hg_init_info`.  As the code is written right now, though, that struct is not  passed directly through to Mercury.  It is used to populate corresponding json fields in `validate_and_complete_config()` if necessary, then a new `hg_init_info` is declared and initialized on the stack and populated from the fully realized json (which may include the union of default parameter values, values set via json, and values set via the args->hg_init_info struct).

This means that the only parameters that can be set via args->hg_init_info() are those recognized and directly supported by margo; it cannot be used to pass in explicit settings to Mercury directly.

Is this intentional?  If so we need to be careful track the Mercury hg_init_info struct as new fields become available.  If not, we need to allow unrecognized fields to fall through unmodified so that there is an interim way to support Mercury settings that aren't available in the margo json format.

**Comment by carns** [comment]
We should also clarify the function documentation either way as well so its clear to users.

**Comment by mdorier** [comment]
I think if we want to propagate any extra fields, we can just add a line after https://github.com/mochi-hpc/mochi-margo/blob/main/src/margo-init.c#L107 :
```c
if(args.hg_init_info) memcpy(&hg_init_info, &args.hg_init_info, sizeof(hg_init_info));
```
Would that work for you?

**Comment by carns** [comment]
That sounds right to me.

**Comment by carns** [comment]
Thanks @mdorier.  I'm closing this issue for now (confirmed fix in a local build).  I'll open a couple of separate issues from here: one for margo to report the existing config (low priority, to be resolved once that linked mercury issue is resolved), and one to support the device memory option in our json.
