### ISSUE TITLE
Fix breadcrumb system in scenarios that involve different ULTs

### ISSUE THREAD

**Issue by mdorier** [mochi-hpc/mochi-margo#208]
With the current way we are handling breadcrumbs and profiling data, if an RPC handler creates a ULT and calls `margo_respond` from that ULT, `margo_respond` won't find timing data [here](https://github.com/mochi-hpc/mochi-margo/blob/5d7eff42ffb4a80a28c5baf6b8d94a65f1f175b0/src/margo-core.c#L1133), and in fact will likely crash at [this assert](https://github.com/mochi-hpc/mochi-margo/blob/5d7eff42ffb4a80a28c5baf6b8d94a65f1f175b0/src/margo-core.c#L1134) if profiling is enabled. Similarly if we call `margo_forward` in a ULT that is not the handler's ULT, [this function](https://github.com/mochi-hpc/mochi-margo/blob/5d7eff42ffb4a80a28c5baf6b8d94a65f1f175b0/src/margo-diag.c#L248) will not pick up the context, and we won't get any lineage data.

We have several tools to solve this:
- First, `HG_Set_data` could be used to associate timing/breadcrumb data with a handle when it is created. This way we can recover the breadcrumb information in `margo_respond` wherever it is called;
- We can also keep the `ABT_set/get_key` mechanism for simplicity to recover information when `margo_forward` is called from the same ULT as the handler;
- We would need a way to propagate a breadcrumb to a new handle if the handle is created in a different ULT. This could be done via a pair of function `uint64_t margo_get_breadcrumb(hg_handle_t handle)` and `void margo_recover_parent_breadcrumb(hg_handle_t handle, uint64_t breadcrumb)`.

**Comment by carns** [comment]
For the 3rd bullet I started to say that maybe we could look into an argobots mechanism to relay keys to child ULTs.  That still would not be complete though, since technically any number of mechanisms could be used to relay control flow to another ULT, its not necessarily just ABT_thread_create().

We could wait and solve that one when we have a need for it?  The first order problems will be to fix assertions and make sure we can at least carry breadcrumbs across handles.

**Comment by mdorier** [comment]
Yeah I was also thinking of asking the Argobots devs to add a ULT attribute that says "inherit keys from the calling ULT", but that doesn't solve the problem in that it still requires the user to add this attribute. So we might as well provide a function that explicitly propagates the breadcrumb.

**Comment by mdorier** [comment]
This is fixed by the new monitoring system.
