### ISSUE TITLE
link errors with json-c 0.13

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#225]
The OLCF Crusher system has json-c 0.13 available as a system library.  This worked Ok at some point, but now produces this link error:

```
  CCLD     src/margo-info
/usr/bin/ld: src/.libs/libmargo.so: undefined reference to `json_object_new_array_ext'
/usr/bin/ld: src/.libs/libmargo.so: undefined reference to `json_object_new_uint64'
```

Does this mean that mochi-margo requires a newer version of json-c?  Or is this a different problem?

This is a little bit tricky on the Crusher software stack because something else in the default toolchain (MPI?) is already linking in 0.13.  If we need a newer one then we may have to work out a conflict here.

**Comment by mdorier** [comment]
Indeed, it looks like the json-c developers added `json_object_new_uint64` in version 0.14 and `json_object_new_array_ext` in 0.15. I'll look into using the version macros from json-c to check if we can use them.

**Comment by mdorier** [comment]
Fixed (I pushed directly to main). I test with json-c 0.16.0 and 0.13.1. Could you check on Crusher and close the issue if it works fine?

**Comment by carns** [comment]
Confirmed fix- thanks!
