### ISSUE TITLE
Some issues in building the latest main branch

### ISSUE THREAD

**Issue by Zhang690683220** [mochi-hpc/mochi-margo#234]
Hi,

I got a lot of redefine warnings for `PACKAGE_STRING` `PACKAGE_VERSION` and `VERSION`.

Also, I got another error in
```
src/margo-core.c: In function 'margo_deregister':
src/margo-core.c:545:32: error: storage size of 'pool_info' isn't known
  545 |         struct margo_pool_info pool_info;
```
```
src/margo-core.c: In function 'margo_register_internal':
src/margo-core.c:2056:28: error: storage size of 'pool_info' isn't known
 2056 |     struct margo_pool_info pool_info;
```

**Comment by mdorier** [comment]
What compiler are you using? So i can try reproducing the error.

**Comment by mdorier** [comment]
I tried the current `main` branch with both gcc 11.3.0 and clang 14.0.0, everything looks fine, not even a single warning with `-Wall -Wextra -Wpedantic`...

**Comment by carns** [comment]
Hi @Zhang690683220 , that `struct margo_pool_info` is a new struct that is defined in margo-config.h, which is now provided in the source tree but _used_ to be auto-generated by autoconf in the build tree.  I suspect there is some confusion in your build where maybe it is including an auto-generated margo-config.h from a previous build instead of the source tree one that it is supposed to use in newer versions of Margo.

Can you try a pure clean build in a new directory to check?

**Comment by mdorier** [comment]
It's actually defined in `margo-abt-config.h`, not `margo-config.h`...

**Comment by carns** [comment]
In main?

```
carns-x1-7g ~/w/s/m/m/include (main=)> grep margo_pool_info *
margo-config.h:struct margo_pool_info {
margo-config.h: * @param [out] info Pointer to margo_pool_info struct to fill.
margo-config.h:                                      struct margo_pool_info* info);
margo-config.h: * @param [out] info Pointer to margo_pool_info struct to fill.
margo-config.h:                                    struct margo_pool_info* info);
margo-config.h: * @param [out] info Pointer to margo_pool_info struct to fill.
margo-config.h:                                     struct margo_pool_info* info);
```

**Comment by mdorier** [comment]
Oh my bad, I confused it with `struct margo_abt_pool`.

**Comment by mdorier** [comment]
Can you tell me the version of json-c?

**Comment by Zhang690683220** [comment]
it should be json-c-0.13 on their system.

**Comment by mdorier** [comment]
Ok it's an old version. I thought I had provided workaround for that, let me check.

**Comment by mdorier** [comment]
I pushed a commit to fix the problem. Can you retry?

**Comment by Zhang690683220** [comment]
Ok. It works now. Thank you.

**Comment by mdorier** [comment]
Great! Closing.
