### ISSUE TITLE
[warning] Destroying a pool ... is always displayed in margo_finalize()

### ISSUE THREAD

**Issue by otatebe** [mochi-hpc/mochi-margo#240]
Even using this sample program in
https://mochi.readthedocs.io/en/latest/margo/02_hello.html

margo_finalize() displays the following message.

```
$ ./client "..."
[info] Hello World!
[warning] Destroying a pool (__primary__) still potentially used by 1 RPCs
```

This occurs after this commit ad71b181c23a7d6757c0515ab781aa06e7214638

**Comment by mdorier** [comment]
Thanks for reporting. The latest version of Margo allows adding and removing pools at run time, so Margo is trying to be helpful by telling you if you're removing a pool that *could* still be used by RPCs. Arguably this does not matter when you're finalizing. I'll update to make sure you don't get warnings about that at finalization time.

**Comment by mdorier** [comment]
Ok it's removed.
