### ISSUE TITLE
[SYMBIOSYS] [BUG] [DIAGNOSTICS] Issue with the analysis and display of the diagnostics information

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#63]
It appears that the low watermark and highwatermark columns are interchanged. Further, on some occasions, the data itself doesn't make sense. @carns discovered the following issue:
Margo diagnostics

#Addr Hash and Address Name: 18446744056162363849,na+sm://365924/0
Thu Aug 27 13:40:19 2020
Function Name, Average Time Per Call, Cumulative Time, Highwatermark, Lowwatermark, Call Count

trigger_elapsed,0.000000086,0.056649923,0.000000000,0.000028849,655365 progress_elapsed_zero_timeout,0.000000158,0.020703077,0.000000238,0.000006199,131073 progress_elapsed_nonzero_timeout,0.000000968,0.126827478,0.100276709,0.100276709,131073 bulk_create_elapsed,0.000000091,0.011901140,0.000000238,0.000016689,131072

**Comment by carns** [comment]
In GitLab by @srini009 on Aug 27, 2020, 14:12

changed title from **[MARGO DIAGNOSTICS] Issue with the analysis display of the diagnostics information** to **[MARGO DIAGNOSTICS] Issue with the analysis {+and +}display of the diagnostics information**

**Comment by carns** [comment]
In GitLab by @srini009 on Dec 15, 2020, 22:37

changed title from **[{-MARGO -}DIAGNOSTICS] Issue with the analysis and display of the diagnostics information** to **[{+SYMBIOSYS] [BUG] [+}DIAGNOSTICS] Issue with the analysis and display of the diagnostics information**

**Comment by mdorier** [comment]
No longer relevant after new monitoring system. Closing issue.
