### ISSUE TITLE
[SYMBIOSYS]FEATURE] Add system stats sampling ULT and corresponding profile generation script

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#70]
* Node-level metric summary.
* ULT runs periodically to sample a range of basic node-level metrics and the analysis script plots these metrics over time, and across nodes.
* No callpath information is tagged; purely a hardware-resource view.

**Comment by mdorier** [comment]
No longer relevant after new monitoring system. Closing issue.
