### ISSUE TITLE
[SYMBIOSYS][FEATURE] Add distributed tracing capability and corresponding trace generation script

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#71]
* Implement distributed request tracing using metadata propagation
* Capture individual request structure, output Zipkin-compatible JSON-files.
* Instrumentation points remain the same as for breadcrumb profiling.
* Capture samples of memory usage, Argobots queue length while performing trace measurement.
* Ability to correlate lower-level metric usage with specific request callpaths.
* Conversely, ability to analyze these metric values along the entire request path.

**Comment by mdorier** [comment]
No longer relevant after new monitoring system. Closing issue.
