### ISSUE TITLE
[SYMBIOSYS][FEATURE] Add capability to infer network bandwidth from a distributed trace

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#72]
* Using the data gathered from bulk transfer times and “Target Operation Time” (new API call), trace analysis enables
 * Inferring “effective” network b/w for bulk transfer call
 * Inferring “effective” storage op. b/w for database operation (provided microservice adds necessary instr.)
 * Analysis can be done to extract these plots on a per-host and/or per-callpath basis.

**Comment by mdorier** [comment]
No longer relevant after new monitoring system. Closing issue.
